name: flutter_beer_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  go_router: ^12.0.0
  bloc_concurrency: ^0.2.2
  lottie: ^2.7.0
  icons_plus: ^4.0.0
  supabase_flutter: ^1.10.25
  google_sign_in: ^6.1.6
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/loading.json
    - assets/cir_load.json
    - assets/welcome.json
